# Google Cloud Build configuration for CI/CD
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/revive-impact:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/revive-impact:latest'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/revive-impact:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/revive-impact:latest'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'revive-impact'
      - '--image'
      - 'gcr.io/$PROJECT_ID/revive-impact:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/revive-impact:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/revive-impact:latest'

# Build timeout
timeout: 1200s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
